using System;
using System.Collections.Generic;
using System.Numerics;
using Xunit;

namespace LaunchDarkly.EventSource.Tests
{
    public class ExponentialBackoffWithDecorrelationTest
    {
        private static readonly TimeSpan Base1s = TimeSpan.FromMilliseconds(1000);
        private static readonly TimeSpan Max30s = TimeSpan.FromMilliseconds(30000);

        private static ExponentialBackoffWithDecorrelation Seeded(TimeSpan min, TimeSpan max,
            int seed = 12345) =>
            new ExponentialBackoffWithDecorrelation(min, max, new Random(seed));

        [Fact]
        public void Exponential_backoff_should_not_exceed_maximum()
        {
            ExponentialBackoffWithDecorrelation expo =
                new ExponentialBackoffWithDecorrelation(Base1s, Max30s);

            var backoff = expo.GetNextBackOff();

            Assert.True(backoff <= Max30s);
        }

        [Fact]
        public void Exponential_backoff_should_not_exceed_maximum_in_test_loop()
        {
            ExponentialBackoffWithDecorrelation expo =
                new ExponentialBackoffWithDecorrelation(Base1s, Max30s);

            for (int i = 0; i < 100; i++)
            {
                var backoff = expo.GetNextBackOff();

                Assert.True(backoff <= Max30s);
            }
        }

        [Fact]
        public void Exponential_backoff_should_reset_when_backoff_n_resets()
        {
            ExponentialBackoffWithDecorrelation expo =
                new ExponentialBackoffWithDecorrelation(Base1s, Max30s);

            for (int i = 0; i < 100; i++)
            {
                expo.GetNextBackOff();
            }
            expo.ResetBackoffN();
            // Backoffs use jitter, so assert that the reset backoff time isn't more than double the minimum
            Assert.True(expo.GetNextBackOff() <= TimeSpan.FromMilliseconds(2000));
        }

        // ---- parity with the previous implementation ----

        // These expectations were generated by running the algorithm this class replaced --
        // Convert.ToInt32(Math.Min(max.TotalMilliseconds, min.TotalMilliseconds * Math.Pow(2, level)))
        // -- so the rewrite is pinned to the delays the library produced before it. The former
        // algorithm threw OverflowException for a maximum above int.MaxValue milliseconds; those
        // inputs have no previous behavior to match and are covered separately below.
        [Theory]
        // library defaults
        [InlineData(1000, 30000, 0, 1000L)]
        [InlineData(1000, 30000, 1, 2000L)]
        [InlineData(1000, 30000, 2, 4000L)]
        [InlineData(1000, 30000, 3, 8000L)]
        [InlineData(1000, 30000, 4, 16000L)]
        [InlineData(1000, 30000, 5, 30000L)]
        [InlineData(1000, 30000, 6, 30000L)]
        [InlineData(1000, 30000, 7, 30000L)]
        [InlineData(1000, 30000, 8, 30000L)]
        // low ceiling
        [InlineData(1000, 3000, 0, 1000L)]
        [InlineData(1000, 3000, 1, 2000L)]
        [InlineData(1000, 3000, 2, 3000L)]
        [InlineData(1000, 3000, 3, 3000L)]
        [InlineData(1000, 3000, 4, 3000L)]
        // min above max
        [InlineData(5000, 1000, 0, 1000L)]
        [InlineData(5000, 1000, 1, 1000L)]
        [InlineData(5000, 1000, 2, 1000L)]
        // min equals max
        [InlineData(1000, 1000, 0, 1000L)]
        [InlineData(1000, 1000, 1, 1000L)]
        [InlineData(1000, 1000, 2, 1000L)]
        // ceiling is an exact power-of-two multiple
        [InlineData(1000, 32000, 0, 1000L)]
        [InlineData(1000, 32000, 1, 2000L)]
        [InlineData(1000, 32000, 2, 4000L)]
        [InlineData(1000, 32000, 3, 8000L)]
        [InlineData(1000, 32000, 4, 16000L)]
        [InlineData(1000, 32000, 5, 32000L)]
        [InlineData(1000, 32000, 6, 32000L)]
        // zero min
        [InlineData(0, 30000, 0, 0L)]
        [InlineData(0, 30000, 1, 0L)]
        [InlineData(0, 30000, 2, 0L)]
        // zero max
        [InlineData(1000, 0, 0, 0L)]
        [InlineData(1000, 0, 1, 0L)]
        [InlineData(1000, 0, 2, 0L)]
        // one millisecond
        [InlineData(1, 1, 0, 1L)]
        [InlineData(1, 1, 1, 1L)]
        [InlineData(1, 1, 2, 1L)]
        // temporary bounds used in tests
        [InlineData(60, 500, 0, 60L)]
        [InlineData(60, 500, 1, 120L)]
        [InlineData(60, 500, 2, 240L)]
        [InlineData(60, 500, 3, 480L)]
        [InlineData(60, 500, 4, 500L)]
        [InlineData(60, 500, 5, 500L)]
        // extended regime: 5 min to 1 hr
        [InlineData(300000, 3600000, 0, 300000L)]
        [InlineData(300000, 3600000, 1, 600000L)]
        [InlineData(300000, 3600000, 2, 1200000L)]
        [InlineData(300000, 3600000, 3, 2400000L)]
        [InlineData(300000, 3600000, 4, 3600000L)]
        [InlineData(300000, 3600000, 5, 3600000L)]
        [InlineData(300000, 3600000, 6, 3600000L)]
        // ceiling at int.MaxValue ms
        [InlineData(1000, 2147483647, 0, 1000L)]
        [InlineData(1000, 2147483647, 1, 2000L)]
        [InlineData(1000, 2147483647, 2, 4000L)]
        [InlineData(1000, 2147483647, 3, 8000L)]
        [InlineData(1000, 2147483647, 4, 16000L)]
        [InlineData(1000, 2147483647, 5, 32000L)]
        [InlineData(1000, 2147483647, 6, 64000L)]
        [InlineData(1000, 2147483647, 7, 128000L)]
        [InlineData(1000, 2147483647, 8, 256000L)]
        [InlineData(1000, 2147483647, 9, 512000L)]
        [InlineData(1000, 2147483647, 10, 1024000L)]
        [InlineData(1000, 2147483647, 11, 2048000L)]
        [InlineData(1000, 2147483647, 12, 4096000L)]
        [InlineData(1000, 2147483647, 13, 8192000L)]
        [InlineData(1000, 2147483647, 14, 16384000L)]
        [InlineData(1000, 2147483647, 15, 32768000L)]
        [InlineData(1000, 2147483647, 16, 65536000L)]
        [InlineData(1000, 2147483647, 17, 131072000L)]
        [InlineData(1000, 2147483647, 18, 262144000L)]
        [InlineData(1000, 2147483647, 19, 524288000L)]
        [InlineData(1000, 2147483647, 20, 1048576000L)]
        [InlineData(1000, 2147483647, 21, 2097152000L)]
        [InlineData(1000, 2147483647, 22, 2147483647L)]
        [InlineData(1000, 2147483647, 23, 2147483647L)]
        [InlineData(1000, 2147483647, 24, 2147483647L)]
        public void MatchesPreviousImplementation(long minMillis, long maxMillis, int level,
            long expected)
        {
            var expo = Seeded(TimeSpan.FromMilliseconds(minMillis),
                TimeSpan.FromMilliseconds(maxMillis));

            Assert.Equal(expected, expo.GetUnjitteredMillisecondsForN(level));
        }

        // ---- delay math ----

        [Fact]
        public void DelayDoublesPerN()
        {
            var expo = Seeded(Base1s, Max30s);

            Assert.Equal(1000L, expo.GetUnjitteredMillisecondsForN(0));
            Assert.Equal(2000L, expo.GetUnjitteredMillisecondsForN(1));
            Assert.Equal(4000L, expo.GetUnjitteredMillisecondsForN(2));
            Assert.Equal(8000L, expo.GetUnjitteredMillisecondsForN(3));
            Assert.Equal(16000L, expo.GetUnjitteredMillisecondsForN(4));
        }

        [Fact]
        public void DelayClampsAtMaximum()
        {
            var expo = Seeded(Base1s, TimeSpan.FromMilliseconds(3000));

            Assert.Equal(1000L, expo.GetUnjitteredMillisecondsForN(0));
            Assert.Equal(2000L, expo.GetUnjitteredMillisecondsForN(1));
            Assert.Equal(3000L, expo.GetUnjitteredMillisecondsForN(2));
            Assert.Equal(3000L, expo.GetUnjitteredMillisecondsForN(3));
        }

        [Fact]
        public void DelayReachesMaximumExactlyWhenItIsAPowerOfTwoMultiple()
        {
            // The boundary the ceiling comparison has to get right: min << level == max exactly.
            var expo = Seeded(Base1s, TimeSpan.FromMilliseconds(32000));

            Assert.Equal(16000L, expo.GetUnjitteredMillisecondsForN(4));
            Assert.Equal(32000L, expo.GetUnjitteredMillisecondsForN(5));
            Assert.Equal(32000L, expo.GetUnjitteredMillisecondsForN(6));
        }

        [Fact]
        public void DelayOneBelowAPowerOfTwoCeilingIsCapped()
        {
            var expo = Seeded(Base1s, TimeSpan.FromMilliseconds(31999));

            Assert.Equal(16000L, expo.GetUnjitteredMillisecondsForN(4));
            Assert.Equal(31999L, expo.GetUnjitteredMillisecondsForN(5));
        }

        [Fact]
        public void DelayWithZeroBaseIsAlwaysZero()
        {
            var expo = Seeded(TimeSpan.Zero, Max30s);

            Assert.Equal(0L, expo.GetUnjitteredMillisecondsForN(0));
            Assert.Equal(0L, expo.GetUnjitteredMillisecondsForN(5));
        }

        [Fact]
        public void DelayWithZeroMaximumIsAlwaysZero()
        {
            var expo = Seeded(Base1s, TimeSpan.Zero);

            Assert.Equal(0L, expo.GetUnjitteredMillisecondsForN(0));
            Assert.Equal(0L, expo.GetUnjitteredMillisecondsForN(5));
        }

        [Fact]
        public void DelayWithBaseAboveMaximumIsClampedToMaximum()
        {
            var expo = Seeded(TimeSpan.FromMilliseconds(5000), TimeSpan.FromMilliseconds(1000));

            Assert.Equal(1000L, expo.GetUnjitteredMillisecondsForN(0));
            Assert.Equal(1000L, expo.GetUnjitteredMillisecondsForN(3));
        }

        [Theory]
        [InlineData(0)]
        [InlineData(1)]
        [InlineData(62)]
        [InlineData(63)]
        [InlineData(64)]
        [InlineData(1000)]
        [InlineData(int.MaxValue)]
        public void HighBackoffNDoesNotOverflow(int level)
        {
            // Levels at and beyond 63 matter specifically: C# masks a 64-bit shift count to its
            // low 6 bits, so a missing guard would silently produce a wrong value rather than
            // fail loudly.
            var expo = Seeded(Base1s, Max30s);

            Assert.InRange(expo.GetUnjitteredMillisecondsForN(level), 1000L, 30000L);
        }

        [Theory]
        [InlineData(0)]
        [InlineData(22)]
        [InlineData(62)]
        [InlineData(63)]
        [InlineData(64)]
        [InlineData(int.MaxValue)]
        public void HugeMaximumNeverOverflows(int level)
        {
            // The previous implementation threw OverflowException here once the level passed 21,
            // and that exception surfaced outside the reconnect loop's try/catch, permanently
            // stopping the stream.
            var expo = Seeded(Base1s, TimeSpan.MaxValue);

            Assert.True(expo.GetUnjitteredMillisecondsForN(level) >= 1000L);
        }

        [Fact]
        public void NegativeNIsTreatedAsZero()
        {
            var expo = Seeded(Base1s, Max30s);

            Assert.Equal(1000L, expo.GetUnjitteredMillisecondsForN(-1));
        }

        [Fact]
        public void SubMillisecondBoundsTruncateToZero()
        {
            // Delays are whole milliseconds, so a bound below 1ms rounds down to nothing. The
            // previous implementation kept fractional milliseconds in a double and would have
            // produced 1ms at level 1 from a 0.5ms minimum.
            var expo = Seeded(TimeSpan.FromTicks(5000), TimeSpan.FromMilliseconds(1000));

            Assert.Equal(0L, expo.GetUnjitteredMillisecondsForN(0));
            Assert.Equal(0L, expo.GetUnjitteredMillisecondsForN(1));
        }

        [Fact]
        public void MaximumAboveIntRangeIsReturnedIntact()
        {
            // A ceiling beyond int.MaxValue milliseconds must survive as a long; only the jitter
            // bound saturates to int.
            var big = TimeSpan.FromMilliseconds(5_000_000_000L);
            var expo = Seeded(Base1s, big);

            Assert.Equal(5_000_000_000L, expo.GetUnjitteredMillisecondsForN(40));
        }

        // ---- server-directed minimum delay (SSE "retry:" field) ----

        [Fact]
        public void ServerDirectedMinDelayOverridesConfiguredMinimum()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(5000));

            Assert.Equal(5000L, expo.GetUnjitteredMillisecondsForN(0));
            Assert.Equal(10000L, expo.GetUnjitteredMillisecondsForN(1));
        }

        [Fact]
        public void ServerDirectedMinDelayOverridesTemporaryMinimum()
        {
            var expo = Seeded(Base1s, TimeSpan.FromHours(1));
            expo.SetBounds(TimeSpan.FromMinutes(5), TimeSpan.FromHours(1));

            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(5000));

            // The directed value wins over the temporary minimum, not just the configured one.
            Assert.Equal(5000L, expo.GetUnjitteredMillisecondsForN(0));
        }

        [Fact]
        public void ServerDirectedMinDelayResetsN()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.GetNextBackOff();
            expo.GetNextBackOff();
            expo.GetNextBackOff();
            Assert.Equal(3, expo.GetBackoffN());

            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(5000));

            // So the next attempt uses the directed value itself rather than doubling from
            // wherever the progression had reached.
            Assert.Equal(0, expo.GetBackoffN());
        }

        [Fact]
        public void ZeroServerDirectedMinDelayProducesZeroDelay()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.SetServerDirectedMinDelay(TimeSpan.Zero);

            Assert.Equal(0L, expo.GetUnjitteredMillisecondsForN(0));
            Assert.Equal(0L, expo.GetUnjitteredMillisecondsForN(5));
            Assert.Equal(TimeSpan.Zero, expo.GetNextBackOff());
        }

        [Fact]
        public void NegativeServerDirectedMinDelayBecomesZero()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(-5));

            Assert.Equal(TimeSpan.Zero, expo.GetServerDirectedMinDelay());
        }

        [Fact]
        public void ServerDirectedMinDelayIsStillLimitedByTheMaximum()
        {
            var expo = Seeded(Base1s, TimeSpan.FromMilliseconds(2000));

            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(5000));

            // The ceiling is never affected by a directed value, so it still bounds the delay.
            Assert.Equal(2000L, expo.GetUnjitteredMillisecondsForN(0));
        }

        [Fact]
        public void ServerDirectedMinDelayDoesNotRevertTheTemporaryCeiling()
        {
            // Configured ceiling 30s, temporary ceiling 1hr, then a directed value arrives.
            var expo = Seeded(Base1s, Max30s);
            expo.SetBounds(TimeSpan.FromMinutes(5), TimeSpan.FromHours(1));

            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(300));

            Assert.Equal(TimeSpan.FromHours(1), expo.GetMaximumDelay());

            // Reading at n = 0 cannot tell the two apart -- both would give 300. These levels
            // can: doubling 300ms reaches the configured 30s ceiling by n = 7, so an
            // implementation that reverted the regime would report 30000 here instead.
            Assert.Equal(2457600L, expo.GetUnjitteredMillisecondsForN(13));
            Assert.Equal(3600000L, expo.GetUnjitteredMillisecondsForN(14));
            Assert.Equal(3600000L, expo.GetUnjitteredMillisecondsForN(62));
        }

        [Fact]
        public void ServerDirectedMinDelaySurvivesSetBounds()
        {
            var expo = Seeded(Base1s, TimeSpan.FromHours(1));
            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(5000));

            expo.SetBounds(TimeSpan.FromMinutes(5), TimeSpan.FromHours(1));

            Assert.Equal(TimeSpan.FromMilliseconds(5000), expo.GetServerDirectedMinDelay());
            Assert.Equal(5000L, expo.GetUnjitteredMillisecondsForN(0));
        }

        [Fact]
        public void ServerDirectedMinDelaySurvivesResetBackoffN()
        {
            var expo = Seeded(Base1s, Max30s);
            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(5000));

            expo.ResetBackoffN();

            Assert.Equal(TimeSpan.FromMilliseconds(5000), expo.GetServerDirectedMinDelay());
            Assert.Equal(5000L, expo.GetUnjitteredMillisecondsForN(0));
        }

        [Fact]
        public void LaterServerDirectedMinDelayReplacesEarlier()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(5000));
            expo.SetServerDirectedMinDelay(TimeSpan.FromMilliseconds(7000));

            Assert.Equal(TimeSpan.FromMilliseconds(7000), expo.GetServerDirectedMinDelay());
            Assert.Equal(7000L, expo.GetUnjitteredMillisecondsForN(0));
        }

        [Fact]
        public void NoServerDirectedMinDelayByDefault()
        {
            var expo = Seeded(Base1s, Max30s);

            Assert.Null(expo.GetServerDirectedMinDelay());
        }

        // ---- jitter ----

        [Fact]
        public void JitteredDelayStaysBetweenHalfAndFullOfUnjitteredValue()
        {
            var expo = Seeded(Base1s, Max30s);

            for (int level = 0; level < 8; level++)
            {
                long unjittered = expo.GetUnjitteredMillisecondsForN(level);
                var delay = expo.GetNextBackOff();

                Assert.InRange(delay.TotalMilliseconds, unjittered / 2, unjittered);
            }
        }

        [Fact]
        public void JitterAppliesToAMaximumAboveIntRangeWithoutThrowing()
        {
            // The jitter bound saturates at int.MaxValue; the delay itself must stay a long.
            var expo = Seeded(TimeSpan.FromMilliseconds(4_000_000_000L),
                TimeSpan.FromMilliseconds(8_000_000_000L));

            var delay = expo.GetNextBackOff();

            Assert.InRange(delay, TimeSpan.FromMilliseconds(2_000_000_000L),
                TimeSpan.FromMilliseconds(4_000_000_000L));
        }

        [Fact]
        public void ZeroDelayProducesZeroWithoutThrowing()
        {
            var expo = Seeded(TimeSpan.Zero, TimeSpan.Zero);

            Assert.Equal(TimeSpan.Zero, expo.GetNextBackOff());
            Assert.Equal(TimeSpan.Zero, expo.GetNextBackOff());
        }

        [Fact]
        public void TinyMinimumDelayProducesNoJitter()
        {
            // With a 1ms base the integer arithmetic leaves no room for a jitter component.
            var expo = Seeded(TimeSpan.FromMilliseconds(1), TimeSpan.FromMilliseconds(1));

            Assert.Equal(TimeSpan.Zero, expo.GetNextBackOff());
        }

        [Fact]
        public void SeededRandomProducesDeterministicDelays()
        {
            var a = Seeded(Base1s, Max30s);
            var b = Seeded(Base1s, Max30s);

            for (int i = 0; i < 5; i++)
            {
                Assert.Equal(a.GetNextBackOff(), b.GetNextBackOff());
            }
        }

        [Fact]
        public void DelaysAreWholeMilliseconds()
        {
            // Nothing in the delay path passes through a floating-point value, so every result
            // lands on a millisecond boundary.
            var expo = Seeded(Base1s, Max30s);

            for (int i = 0; i < 10; i++)
            {
                var delay = expo.GetNextBackOff();
                Assert.Equal(0, delay.Ticks % TimeSpan.TicksPerMillisecond);
            }
        }

        // ---- n ----

        [Fact]
        public void SetBoundsResetsBackoffN()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.GetNextBackOff();
            expo.GetNextBackOff();
            expo.GetNextBackOff();
            Assert.Equal(3, expo.GetBackoffN());

            expo.SetBounds(TimeSpan.FromMinutes(5), TimeSpan.FromHours(1));

            Assert.Equal(0, expo.GetBackoffN());
        }

        [Fact]
        public void ResetBackoffNReturnsToZero()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.GetNextBackOff();
            expo.GetNextBackOff();

            expo.ResetBackoffN();

            Assert.Equal(0, expo.GetBackoffN());
        }

        [Fact]
        public void SetBoundsWithSameValuesIsNoOp()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.GetNextBackOff();
            expo.GetNextBackOff();
            Assert.Equal(2, expo.GetBackoffN());

            expo.SetBounds(Base1s, Max30s);

            Assert.Equal(2, expo.GetBackoffN());
        }

        [Fact]
        public void SetBoundsRepeatedlyWithSameValuesDoesNotPinTheDelay()
        {
            var expo = Seeded(TimeSpan.FromMinutes(5), TimeSpan.FromHours(1));

            // A caller reapplying identical bounds on every failure must still see the backoff
            // level advance.
            for (int i = 0; i < 4; i++)
            {
                expo.SetBounds(TimeSpan.FromMinutes(5), TimeSpan.FromHours(1));
                expo.GetNextBackOff();
            }

            Assert.Equal(4, expo.GetBackoffN());
        }

        [Fact]
        public void SetBoundsAppliesNewValues()
        {
            var expo = Seeded(Base1s, Max30s);

            expo.SetBounds(TimeSpan.FromMinutes(5), TimeSpan.FromHours(1));

            Assert.Equal(TimeSpan.FromMinutes(5), expo.GetMinimumDelay());
            Assert.Equal(TimeSpan.FromHours(1), expo.GetMaximumDelay());
            Assert.Equal((long)TimeSpan.FromMinutes(5).TotalMilliseconds,
                expo.GetUnjitteredMillisecondsForN(0));
        }

        [Fact]
        public void NegativeBoundsClampToZero()
        {
            var expo = Seeded(TimeSpan.FromMilliseconds(-1000), TimeSpan.FromMilliseconds(-1));

            Assert.Equal(TimeSpan.Zero, expo.GetMinimumDelay());
            Assert.Equal(TimeSpan.Zero, expo.GetMaximumDelay());

            expo.SetBounds(TimeSpan.FromMilliseconds(-5), TimeSpan.FromMilliseconds(-5));
            Assert.Equal(TimeSpan.Zero, expo.GetMinimumDelay());
            Assert.Equal(TimeSpan.Zero, expo.GetMaximumDelay());
        }

        [Fact]
        public void SetBoundsToNegativeIsNoOpWhenAlreadyZero()
        {
            var expo = Seeded(TimeSpan.Zero, TimeSpan.Zero);

            expo.GetNextBackOff();
            Assert.Equal(1, expo.GetBackoffN());

            // Clamping happens before the comparison, so this must not reset the backoff level.
            expo.SetBounds(TimeSpan.FromMilliseconds(-10), TimeSpan.FromMilliseconds(-20));
            Assert.Equal(1, expo.GetBackoffN());
        }

        #region Exact reference for the delay formula

        // GetUnjitteredMillisecondsForN computes min << n clamped to max, using shift tricks and an
        // n >= 63 guard to avoid overflowing the 64-bit shift. These two tests check it against an
        // arbitrary-precision reference that cannot overflow, so the optimisation is pinned to the
        // arithmetic it is standing in for rather than to hand-picked expectations.

        private const long MaxTimeSpanMs = 922337203685477L;   // TimeSpan.MaxValue in whole ms

        private static ExponentialBackoffWithDecorrelation FromMillis(long minMs, long maxMs) =>
            new ExponentialBackoffWithDecorrelation(
                TimeSpan.FromTicks(minMs * TimeSpan.TicksPerMillisecond),
                TimeSpan.FromTicks(maxMs * TimeSpan.TicksPerMillisecond));

        private static long ExactReference(long minMs, long maxMs, int n)
        {
            if (minMs <= 0 || maxMs <= 0)
            {
                return 0;
            }
            var exact = new BigInteger(minMs) * BigInteger.Pow(2, n <= 0 ? 0 : n);
            return exact > new BigInteger(maxMs) ? maxMs : (long)exact;
        }

        [Fact]
        public void DelayFormulaMatchesExactReferenceForCuratedBounds()
        {
            // Powers of two and their neighbours, the shipped defaults, the server-directed cap,
            // and the boundaries of int and TimeSpan -- the places a shift or a cast goes wrong.
            var interesting = new long[]
            {
                0, 1, 2, 3, 4, 5, 7, 8, 9, 15, 16, 17, 19, 20, 31, 32, 33, 63, 64, 65,
                99, 100, 127, 128, 129, 255, 256, 999, 1000, 1023, 1024, 1025,
                29999, 30000, 30001, 65535, 65536, 3600000, 86400000,
                int.MaxValue - 1L, int.MaxValue, int.MaxValue + 1L,
                (1L << 31) - 1, 1L << 31, (1L << 40) + 12345,
                MaxTimeSpanMs - 1, MaxTimeSpanMs
            };

            var failures = new List<string>();
            foreach (var min in interesting)
            {
                foreach (var max in interesting)
                {
                    var backoff = FromMillis(min, max);
                    for (var n = -3; n <= 70; n++)   // negatives and n past the 63-bit guard
                    {
                        var actual = backoff.GetUnjitteredMillisecondsForN(n);
                        var expected = ExactReference(min, max, n);
                        if (actual != expected && failures.Count < 20)
                        {
                            failures.Add($"min={min} max={max} n={n} actual={actual} expected={expected}");
                        }
                    }
                }
            }
            Assert.True(failures.Count == 0, string.Join("; ", failures));
        }

        [Fact]
        public void DelayFormulaMatchesExactReferenceForRandomizedBounds()
        {
            // Fixed seed, so a failure is reproducible. The count is deliberately modest: the
            // reference uses BigInteger, and this runs inside the normal suite.
            var random = new Random(12345);
            var failures = new List<string>();
            for (var i = 0; i < 200000; i++)
            {
                var min = NextInclusive(random, 0, MaxTimeSpanMs);
                var max = NextInclusive(random, 0, MaxTimeSpanMs);
                var backoff = FromMillis(min, max);
                for (var k = 0; k < 5; k++)
                {
                    var n = random.Next(-2, 72);
                    var actual = backoff.GetUnjitteredMillisecondsForN(n);
                    var expected = ExactReference(min, max, n);
                    if (actual != expected && failures.Count < 20)
                    {
                        failures.Add($"min={min} max={max} n={n} actual={actual} expected={expected}");
                    }
                }
            }
            Assert.True(failures.Count == 0, string.Join("; ", failures));
        }

        private static long NextInclusive(Random random, long minInclusive, long maxInclusive)
        {
            var buffer = new byte[8];
            random.NextBytes(buffer);
            var value = BitConverter.ToInt64(buffer, 0) & long.MaxValue;
            return minInclusive + value % (maxInclusive - minInclusive + 1);
        }

        #endregion
    }
}
