name: Release Build
description: 'Build in Release Configuration'

runs:
  using: composite
  steps:
    - name: Setup dotnet build tools
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0

    - name: Restore Packages
      shell: bash
      run: dotnet restore

    - name: Build
      shell: bash
      run: dotnet build /p:Configuration=Release ./src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj
